// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY46Hxy_R_RjmfdqiAVt8WL7qUZxmQ7mY',
    appId: '1:710609948614:android:e49206a05c56a3fffaecc7',
    messagingSenderId: '710609948614',
    projectId: 'expensechatapp',
    storageBucket: 'expensechatapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8VORki_wmAoqMY-9tLVHx-HylxQMUe8Y',
    appId: '1:710609948614:ios:cd943cc1bed2a9ddfaecc7',
    messagingSenderId: '710609948614',
    projectId: 'expensechatapp',
    storageBucket: 'expensechatapp.appspot.com',
    androidClientId: '710609948614-6f6bk54h46t0748gqnqegqek4l81r0cu.apps.googleusercontent.com',
    iosClientId: '710609948614-i5ai4hqhqfopko3kd5rqsiecml131jk7.apps.googleusercontent.com',
    iosBundleId: 'com.example.expensechatapp',
  );
}
